<?php

namespace App\Controller;

use App\Model\TasksModel;
use App\Model\UsersModel;

class Tasks extends Table
{
    protected string $tableName = "tasks";

    public function __construct()
    {
        parent::__construct();
        $config = include __DIR__ . "/../../config.php";
        $config["table"] = $this->tableName;
        $this->pageSize = $config["page_size"];
        $this->model = new TasksModel($config);

    }


    public function actionShow(): void
    {
        parent::actionShow(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("Tasks/show");
    }

    public function actionShowAdd(): void
    {
        parent::actionShowAdd(); // TODO: Change the autogenerated stub
        $this
            ->view
            ->addData(["groupList" => $this->model->getGroupList(),
                "loginList" => $this->model->getNameList()])
            ->setTemplate("Tasks/add_edit");
    }

    public function actionShowEdit(): void
    {
        parent::actionShowEdit(); // TODO: Change the autogenerated stub
        $this
            ->view
            ->addData(["groupList" => $this->model->getGroupList(),
                "loginList" => $this->model->getNameList()
//                "performanceList" => $this->model->getPerformance()])
                        ])
            ->setTemplate("Tasks/add_edit");
    }
}