<?php

namespace App\Controller;

use App\Model\TasksModel;

/**
 * Наследует родительский класс Table,
 * перегружает текущие методы из данного класса
 */
class Tasks extends Table
{
    protected string $tableName = "tasks";

    public function __construct()
    {
        parent::__construct();
        $config = include __DIR__ . "/../../config.php";
        $config["table"] = $this->tableName;
        $this->pageSize = $config["page_size"];
        $this->model = new TasksModel($config);
    }

    /**
     * Показывает таблицу
     * @throws \Exception
     */

    public function actionShow(): void
    {
        parent::actionShow(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("Tasks/show");
    }

    /**
     * Показывает страницу для добавления новой строки
     */

    public function actionShowAdd(): void
    {
        parent::actionShowAdd();
        $this
            ->view
            ->addData([
                "groupList" => $this->model->getGroupList(),
                "loginList" => $this->model->getNameList()
            ])
            ->setTemplate("Tasks/add_edit");
    }

    /**
     * Показывает страницу для редактирования строки
     */

    public function actionShowEdit(): void
    {
        parent::actionShowEdit(); // TODO: Change the autogenerated stub
        $this
            ->view
            ->addData(["groupList" => $this->model->getGroupList(),
                "loginList" => $this->model->getNameList()
            ])
            ->setTemplate("Tasks/add_edit");
    }
}