<?php

namespace App\Controller;

class Taskcustomer extends Tasks
{
    public function actionShow(): void
    {
        parent::actionShow(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("Taskcustomer/show");
    }

    public function actionAdd(): void
    {
//        print_r($_POST);
        if ($_POST && array_search("", $_POST) == false && strlen($_POST['discription']) <= 50) {
            parent::actionAdd(); // TODO: Change the autogenerated stub

        } else {
            $this->redirect("?type=Taskcustomer&action=showadd");
        }
    }

    public function actionShowAdd(): void
    {
        parent::actionShowAdd(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("Taskcustomer/add_edit");

    }

}