<?php

namespace App\Controller;

use App\Model\TasksUserModel;

class Taskuser extends Tasks
{
    public function __construct()
    {
        parent::__construct();
        $config = include __DIR__ . "/../../config.php";
        $config["table"] = $this->tableName;
        $this->pageSize = $config["page_size"];
        $this->model = new TasksUserModel($config);
        $this->model->setUserId($_SESSION['user']['id']);
//        print_r($_SESSION['user']['id']);

    }

    public function actionShow(): void
    {
        parent::actionShow(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("Taskuser/show");
    }

    public function actionShowEdit(): void
    {
        parent::actionShowEdit(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("Taskuser/add_edit");

    }
}