<?php

namespace App\Controller;

class Taskuser extends Tasks
{
    public function actionShow(): void
    {
        parent::actionShow(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("Taskuser/show");
    }
}