<?php

namespace App\Controller;

class Taskcustomer extends Tasks
{
    public function actionShow(): void
    {
        parent::actionShow(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("Taskcustomer/show");
    }

}