<?php

namespace App\Controller;

/**
 * Наследует родительский класс Tasks,
 * перегружает метод отображения
 */
class Taskguest extends Tasks
{
    public function actionShow(): void
    {
        parent::actionShow(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("Taskguest/show");
    }
}