<?php

namespace App\Controller;

/**
 * Наследует родительский класс Tasks,
 * перегружает текущие методы отображения
 */
class Taskcustomer extends Tasks
{
    /**
     * Показывает таблицу
     * @throws \Exception
     */

    public function actionShow(): void
    {
        parent::actionShow(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("Taskcustomer/show");
    }

    /**
     * Добавляет новую строку
     */

    public function actionAdd(): void
    {
//        print_r($_POST);
        if ($_POST && array_search("", $_POST) == false && strlen($_POST['discription']) <= 50) {
            parent::actionAdd(); // TODO: Change the autogenerated stub

        } else {
            $this->redirect("?type=Taskcustomer&action=showadd");
        }
    }

    /**
     * Показывает страницу для добавления новой строки
     */

    public function actionShowAdd(): void
    {
        parent::actionShowAdd(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("Taskcustomer/add_edit");

    }

}