<?php

namespace App\Controller;

class Taskguest extends Tasks
{
    public function actionShow(): void
    {
        parent::actionShow(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("Taskguest/show");
    }
//    public function actionShowEdit(): void
//    {
//        $this->redirect("/");
//    }
//
//    public function actionShowAdd(): void
//    {
//        $this->redirect("/");
//    }
//
//    public function actionDel(): void
//    {
//        $this->redirect("/");
//    }
//
//    public function actionAdd(): void
//    {
//        $this->redirect("/");
//    }
//
//    public function actionEdit(): void
//    {
//        $this->redirect("/");
//    }

}