<?php

namespace App\Controller;

use App\Model\TasksUserModel;

class Taskuser extends Tasks
{
    public function __construct()
    {
        parent::__construct();
        $config = include __DIR__ . "/../../config.php";
        $config["table"] = $this->tableName;
        $this->pageSize = $config["page_size"];
        $this->model = new TasksUserModel($config);

    }

    public function actionShow(): void
    {
        parent::actionShow(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("Taskuser/show");
    }
}