<?php


namespace App\Controller;


use App\Model\UserGroupsModel;

/**
 * Подключение к таблице "user_groups"
 */
class Usergroups extends Table
{
    protected string $tableName = "user_groups";

    public function __construct()
    {
        parent::__construct();
        $config = include __DIR__ . "/../../config.php";
        $config["table"] = $this->tableName;
        $this->pageSize = $config["page_size"];
        $this->model = new UserGroupsModel($config);
    }

    public function actionShowEdit(): void
    {
        parent::actionShowEdit(); // TODO: Change the autogenerated stub
        $this
            ->view
            ->addData([
                "new" => $this->model->getRow($_GET["id"]),
                "codeList" => $this->model->getNameGroup()
            ])
            ->setTemplate("Usergroups/add_edit");

    }

//    public function actionShowAdd(): void
//    {
//        parent::actionShowAdd(); // TODO: Change the autogenerated stub
//        $this
//            ->view
//            ->addData([
//                "codeList" => $this->model->getNameGroup(),
//
//                "comments" => $this->model->columnComments(),
//                "action" => "?type=" . ($this->getCurrentClass()) . "&action=add"
//            ])
//
//            ->setTemplate("Usergroups/add_edit");
//    }
}
